name: Go test workflow
on: [push]
#
env:
  APP_ENV: runner
  # Setting an environment variable with the value of a configuration variable
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  #
#
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [  '1.23.1' ]
    #
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
          #cache-dependency-path: subdir/go.sum
      #
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      #
      - name: Install dependencies
        run: go mod tidy
      #
      - name: Build
        run: go build -v ./... 
      #
      - name: Check env.OPENAI_API_KEY
        run: |
            if [ -z "$OPENAI_API_KEY" ]; then
                echo "La variabile OPENAI_API_KEY non è impostata o è vuota."
                exit 0;
            fi
      
      - name: Test with the Go CLI
        run: go test -v ./...
      #
    #
  #